<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Recipes</name>
   <tag></tag>
   <elementGuidId>a1fd380d-5d94-460c-bfad-99a50b25ae33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recipes-submenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='recipes-submenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c8e8936-3a34-47ab-87d8-ce0e5458dfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recipes-submenu</value>
      <webElementGuid>a8301a49-d31b-4991-a90a-62b77a3cfdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Recipes</value>
      <webElementGuid>80ad6867-42fd-4a0a-9556-4b317093f731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/recipes</value>
      <webElementGuid>c2fb6390-f736-4bff-8058-1b3739731981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recipes</value>
      <webElementGuid>2eec8ecb-c4f7-4670-ba9e-e866654224a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recipes-submenu&quot;)</value>
      <webElementGuid>0f3e6c01-cb50-46d3-a7dc-c5d64390da80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='recipes-submenu']</value>
      <webElementGuid>c905abb9-a151-4ae5-a00f-4f74d0f6f635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Recipes')]</value>
      <webElementGuid>2bab4ce5-705e-4b69-b4ff-430fff43c73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/following::a[1]</value>
      <webElementGuid>f1eeecf5-9d35-4b9f-aba1-a3f317fb67c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::a[2]</value>
      <webElementGuid>c074ef70-af65-41ea-93d4-4b3aa4f20b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where to Buy'])[1]/preceding::a[1]</value>
      <webElementGuid>e5968f7f-ef32-44d5-b90c-9c07468581c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recipes']/parent::*</value>
      <webElementGuid>8714f9d0-27cc-40cf-ab22-4b21dfa870fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/recipes')]</value>
      <webElementGuid>09ec7aba-1808-45be-bca7-0bef5267ff5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>10f85f5e-d694-49b1-be8f-b6ab78c4c3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'recipes-submenu' and @href = '/recipes' and (text() = 'Recipes' or . = 'Recipes')]</value>
      <webElementGuid>51842a46-8d0b-4d85-a1fd-3b7bac4500e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
