<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__Old licenses display button</name>
   <tag></tag>
   <elementGuidId>e16ebb0f-f220-4589-a906-79261df68c16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.input-group-text.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30d8482a-921d-45f8-a0bd-87c21ec19029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6aaa52f4-33e6-4fff-9053-54c9b9ad8d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text ng-star-inserted</value>
      <webElementGuid>8da10044-b30e-47cd-b02c-a30ddc26f62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c125-33 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c125-33 ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-4 col-sm-12 mb-4 position-relative&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;input-group-text ng-star-inserted&quot;]</value>
      <webElementGuid>8c02b9ef-4875-4e11-9c22-0e4c551e144a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>08b9ba16-673c-40f0-9e34-93992869872c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div/div[3]/div/button</value>
      <webElementGuid>b041032b-9c5a-49cf-b5ff-8d1fec7501af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::button[1]</value>
      <webElementGuid>1d81d313-ca8a-491b-adc1-0c0243fa68d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حقل مطلوب'])[2]/preceding::button[1]</value>
      <webElementGuid>59eb420d-d7d0-4a4e-a9a6-0f1a1344c118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/button</value>
      <webElementGuid>66e3292f-0eed-478b-95cd-4d1e6434afc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>609a2e9d-1633-4f0b-9487-7cc1f5598c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
