<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__Home</name>
   <tag></tag>
   <elementGuidId>b8018e8e-4327-426a-a800-ed2ad23409f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.custom-icon-size.mdi-home.ng-tns-c55-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-back-logout-items']/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e4007419-c614-4dd4-a384-cb8715615cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi custom-icon-size mdi-home ng-tns-c55-2</value>
      <webElementGuid>257cf349-02ce-4bac-b061-70533a996250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-back-logout-items&quot;)/button[@class=&quot;icon-btn ng-tns-c55-2&quot;]/i[@class=&quot;mdi custom-icon-size mdi-home ng-tns-c55-2&quot;]</value>
      <webElementGuid>34a8a423-35fa-452a-a9c8-e8b78ab4cb1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-back-logout-items']/button[2]/i</value>
      <webElementGuid>597200f8-947b-4e1e-ac31-34a1da5123e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>df7498b5-489e-4a66-a687-06155f6b3799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
