<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FCLQC202228</name>
   <tag></tag>
   <elementGuidId>75efa531-2726-45c2-a7fe-09b315aa5824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-primary.cursor-pointer.text-decoration-underline.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-list-1-content']/tab[2]/div/div/app-table/div/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15c9aaea-7544-407c-b4c3-8f1957990694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary cursor-pointer text-decoration-underline dir-ltr</value>
      <webElementGuid>64c410c6-2b99-4ce3-bca6-4c113ed31496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FCL/QC/2022/28</value>
      <webElementGuid>b67edaa2-1fdc-443a-84b1-c8b569921a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c124-4 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c124-4 ng-star-inserted&quot;]/div[@class=&quot;col-12 ng-star-inserted&quot;]/app-table[1]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;cdk-table table border border-1 ng-star-inserted&quot;]/tbody[1]/tr[@class=&quot;cdk-row ng-star-inserted&quot;]/td[@class=&quot;cdk-cell cdk-column-fullSerial ng-star-inserted&quot;]/span[@class=&quot;text-primary cursor-pointer text-decoration-underline dir-ltr&quot;]</value>
      <webElementGuid>47089bae-7c00-4b4e-bbe3-68099f576444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/div/app-table/div/table/tbody/tr/td/span</value>
      <webElementGuid>1d5a9ca8-1a46-4b40-8eb8-7bc89528ae52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ النشاء'])[1]/following::span[1]</value>
      <webElementGuid>a5b10d2f-2d89-4172-a0e8-2ed9eeec2f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحالة'])[2]/following::span[1]</value>
      <webElementGuid>bc6fcfdd-1189-45f2-a03f-7672e0b0eb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جديد'])[1]/preceding::span[1]</value>
      <webElementGuid>011a17a0-70dd-4212-9413-2e83cc97ef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عربي جديد'])[1]/preceding::span[1]</value>
      <webElementGuid>88039d9f-5d29-452e-b0fa-f87030d18bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FCL/QC/2022/28']/parent::*</value>
      <webElementGuid>7b6f0c1b-7606-4689-921e-3617b58223cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>333a4246-aadb-4bcc-a3bc-30f8c95d014c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'FCL/QC/2022/28' or . = 'FCL/QC/2022/28')]</value>
      <webElementGuid>67b0d9f2-ae8d-4d80-9dda-2938f51ff45f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
