<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>e243944c-a56b-4c5b-9aeb-7784bb04f104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.boxcomps > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/div[3]/table/tbody/tr[2]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>906863e3-72d1-4960-a9bc-f158e2dbce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?c=23945</value>
      <webElementGuid>f83e7fe3-478a-4cf5-83e0-100563af2cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>دوري روشن السعودي</value>
      <webElementGuid>2a098e0f-1f71-41f8-bc69-2553a6aa7202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;localComps mb20&quot;]/table[1]/tbody[1]/tr[2]/td[@class=&quot;boxcomps&quot;]/a[1]</value>
      <webElementGuid>f3d6470f-b214-4727-9cc3-3dc6329800d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/div[3]/table/tbody/tr[2]/td/a</value>
      <webElementGuid>56a1fad0-31ee-4ffb-9fa8-a2132656ec5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'دوري روشن السعودي')]</value>
      <webElementGuid>521e3de7-569d-4c6a-9557-8a9d07549d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسابقات محلية'])[1]/following::a[1]</value>
      <webElementGuid>793e3ffd-75e3-4992-b4ce-64e77a8ae62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دوري يلو الدرجة الأولى السعودي'])[1]/preceding::a[1]</value>
      <webElementGuid>ef43558a-c0a4-422b-b699-e7b5f13d53be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دوري الدرجة الثانية السعودي'])[1]/preceding::a[2]</value>
      <webElementGuid>5e74b638-1b8c-4fd1-9a48-e3c5fc2f2019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='دوري روشن السعودي']/parent::*</value>
      <webElementGuid>8c59e397-b789-45b0-9557-d7ff97154c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?c=23945')]</value>
      <webElementGuid>7bd23ec5-24c2-4786-a650-d907d6e1bc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/table/tbody/tr[2]/td/a</value>
      <webElementGuid>e1820f14-fa65-453f-bd3a-090b66faa8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?c=23945' and (text() = 'دوري روشن السعودي' or . = 'دوري روشن السعودي')]</value>
      <webElementGuid>ee432276-8b76-4e8a-9392-c8e9b62f099e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
