<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__hint--bottom hint--success flags SA</name>
   <tag></tag>
   <elementGuidId>da48ea95-fdf4-44b1-8dd8-7d45a53bebf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hint--bottom.hint--success.flags.SA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[7]/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d1e487e0-e149-4d0d-89a8-2d86701ec711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?y=sa</value>
      <webElementGuid>4b95823e-a1ea-49f8-8587-44274d63a0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hint--bottom hint--success flags SA</value>
      <webElementGuid>53a9a123-6dd6-458d-bcc1-a052c942fca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hint</name>
      <type>Main</type>
      <value>أخبار ومسابقات السعودية</value>
      <webElementGuid>251c163d-da30-417f-832b-19fbb964e435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>أخبار ومسابقات السعودية</value>
      <webElementGuid>adf3e858-cba1-4c9d-82a6-1f0e193bed6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;topHeader&quot;]/div[@class=&quot;headerCont&quot;]/div[@class=&quot;headerFlags&quot;]/a[@class=&quot;hint--bottom hint--success flags SA&quot;]</value>
      <webElementGuid>339fd39f-a817-4875-b43c-47c4844bf4ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[7]/a[7]</value>
      <webElementGuid>3d36552b-14e3-479f-a92e-8bc97d8fef86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?y=sa')]</value>
      <webElementGuid>8a415c2b-3136-472d-97d0-29bedaf1f6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>3dfbc0d3-401c-40bf-a607-918265f4e307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?y=sa']</value>
      <webElementGuid>e4b20554-d161-4aef-be04-8c5aa0d1e4e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
