<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_doom_attachment-full size-full wp-post-image</name>
   <tag></tag>
   <elementGuidId>d2cd05b7-616c-4a46-9ae7-26e0a4c6128f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-full.size-full.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-22619']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ab38a389-1fe6-418f-9ac1-c8736d0e80d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>678</value>
      <webElementGuid>1620f70f-c94f-4a50-aec3-cc2aaded77f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>381</value>
      <webElementGuid>333b8a28-03df-40e8-a679-4046236c8f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uploads.freegogpcgames.com/image/DOOM-1993.jpg</value>
      <webElementGuid>7c60f081-6c58-461d-bc16-eed5474283d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-full size-full wp-post-image</value>
      <webElementGuid>c5c6da94-8d38-4b48-8dcf-ffee91e8f1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>DOOM (1993)</value>
      <webElementGuid>395b70d6-659b-4818-a885-88ba2ea26779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>28d3ab67-afd8-4ec4-a72f-4cd987708096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>bec4dec1-d635-46fe-aae3-13dfdfea93ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-22619&quot;)/div[@class=&quot;inside-article&quot;]/div[@class=&quot;post-image&quot;]/a[1]/img[@class=&quot;attachment-full size-full wp-post-image&quot;]</value>
      <webElementGuid>26670549-7912-4b59-9cae-1ee583f0b302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-22619']/div/div/a/img</value>
      <webElementGuid>341e3566-3aff-49b8-b68d-d35aaba97ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='DOOM (1993)']</value>
      <webElementGuid>156f0b3d-15b2-4956-ab5f-18270008f51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/a/img</value>
      <webElementGuid>65b0ce42-efc6-4248-8765-535df2268ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uploads.freegogpcgames.com/image/DOOM-1993.jpg' and @alt = 'DOOM (1993)']</value>
      <webElementGuid>190e6ea4-dc03-4eec-ac73-8e8b6f3b3393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
