<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>7d87056e-da35-4a84-8ac5-5b81ad1d2017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.gp-icon.icon-search > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>41fe4b8c-70ab-475b-929a-ff457ab45883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
      <webElementGuid>17e4bcde-8550-42fb-a774-65acfbb82759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62d1790f-1fd8-4670-ad9b-f21c85893b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>01386f7d-b4ab-4368-9a3e-6822227f872f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>54878500-d334-4184-ae02-c13b12ec8220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>bccfda9d-d585-4f73-bdbc-3381ab4d8781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-navigation&quot;)/div[@class=&quot;inside-navigation grid-container&quot;]/div[@class=&quot;menu-bar-items&quot;]/span[@class=&quot;menu-bar-item search-item sfHover&quot;]/a[1]/span[@class=&quot;gp-icon icon-search&quot;]/svg[1]</value>
      <webElementGuid>cce02b35-9081-407d-bbcc-6c1dace00443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d9289af2-1320-4440-8e0e-d5eac4fc76ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact/Request'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>b0292bf6-9e19-45ed-bca8-f48cda4b3922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download and install gog DRM-free games on your windows PC!'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>11df5f5b-1f50-4a28-b589-67b0f257b4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get DRM-Free GOG PC Games Now!!!'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>ebcb3aa4-d681-41e9-a398-6a45bbac45cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
